export const FETCH_SHOP_START = 'FETCH_SHOP_START';
export const FETCH_SHOP_SUCCESS = 'FETCH_SHOP_SUCCESS';
export const FETCH_SHOP_FAIL = 'FETCH_SHOP_FAIL'

export const FETCH_SHOPS_START = 'FETCH_SHOPS_START';
export const FETCH_SHOPS_SUCCESS = 'FETCH_SHOPS_SUCCESS';
export const FETCH_SHOPS_FAIL = 'FETCH_SHOPS_FAIL';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const SET_AUTH = 'SET_AUTH';
export const LOGOUT = 'LOGOUT';


